#ifndef _OS_KEYS_H
#define _OS_KEYS_H

namespace os
{
   enum KeyCode
   {
      kKeyNil,
      kKeyA,
      kKeyB,
      kKeyC,
      kKeyD,
      kKeyE,
      kKeyF,
      kKeyG,
      kKeyH,
      kKeyI,
      kKeyJ,
      kKeyK,
      kKeyL,
      kKeyM,
      kKeyN,
      kKeyO,
      kKeyP,
      kKeyQ,
      kKeyR,
      kKeyS,
      kKeyT,
      kKeyU,
      kKeyV,
      kKeyW,
      kKeyX,
      kKeyY,
      kKeyZ,
      kKey0,
      kKey1,
      kKey2,
      kKey3,
      kKey4,
      kKey5,
      kKey6,
      kKey7,
      kKey8,
      kKey9,
      kKey0Pad,
      kKey1Pad,
      kKey2Pad,
      kKey3Pad,
      kKey4Pad,
      kKey5Pad,
      kKey6Pad,
      kKey7Pad,
      kKey8Pad,
      kKey9Pad,
      kKeyF1,
      kKeyF2,
      kKeyF3,
      kKeyF4,
      kKeyF5,
      kKeyF6,
      kKeyF7,
      kKeyF8,
      kKeyF9,
      kKeyF10,
      kKeyF11,
      kKeyF12,
      kKeyEsc,
      kKeyTilde,
      kKeyMinus,
      kKeyEquals,
      kKeyBackspace,
      kKeyTab,
      kKeyOpenbrace,
      kKeyClosebrace,
      kKeyEnter,
      kKeyColon,
      kKeyQuote,
      kKeyBackslash,
      kKeyBackslash2,
      kKeyComma,
      kKeyStop,
      kKeySlash,
      kKeySpace,
      kKeyInsert,
      kKeyDel,
      kKeyHome,
      kKeyEnd,
      kKeyPageUp,
      kKeyPageDown,
      kKeyLeft,
      kKeyRight,
      kKeyUp,
      kKeyDown,
      kKeySlashPad,
      kKeyAsterisk,
      kKeyMinusPad,
      kKeyPlusPad,
      kKeyDelPad,
      kKeyEnterPad,
      kKeyPrtscr,
      kKeyPause,
      kKeyAbntC1,
      kKeyYen,
      kKeyKana,
      kKeyConvert,
      kKeyNoconvert,
      kKeyAt,
      kKeyCircumflex,
      kKeyColon2,
      kKeyKanji,
      kKeyUnknown,

      kKeyFirstModifierKeyCode,

      kKeyLShift,
      kKeyRShift,
      kKeyLControl,
      kKeyRControl,
      kKeyAlt,
      kKeyAltGr,
      kKeyLWin,
      kKeyRWin,
      kKeyMenu,
      kKeyCommand,
      kKeyScrLock,
      kKeyNumLock,
      kKeyCapsLock,

      kTotalKeyCodes
   };

   enum KeyModifiers
   {
      kKeyNoneModifier          = 0,
      kKeyShiftModifier         = 1,
      kKeyCtrlModifier          = 2,
      kKeyAltModifier           = 4,
      kKeyCmdModifier           = 8,
      kKeySpaceModifier         = 16,
      kKeyWinModifier           = 32,
      kKeyUninitializedModifier = 64,
   };
} // namespace os

#endif